### ISSUE TITLE
Change hyperlink URL for images on "About" tab

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-waterfront-access#183]
On the about tab, we need to update the hyperlinks provided for these two features sites:

Shirley Chisholm State Park
https://waterfrontaccess.planning.nyc.gov/#14.64/40.64683/-73.86632

Richmond Terrace Park
https://waterfrontaccess.planning.nyc.gov/#17.69/40.63734/-74.153696

Reasoning: Current clicking on the photos takes you to an external website which is jarring and doesn't help you understand where the parks are physically located.

**Comment by bfreeds** [comment]
@hannahkates just want to confirm the desired behavior here.  Because these two projects are not represented in the Carto `wam_wpaas` table, we don't have a profile for them. 

When a user clicks on one of these pictures from the "about" page, they should be zoomed to the appropriate place on the map, where they could click on the site and then be directed to the external site for more information?

**Comment by hannahkates** [comment]
@bfreeds yes that's correct. we don't have a profile for them, but want users to be able to see where they're located on the map. if they want additional info after that, they can click on the feature on the map to be directed to the external website.
